# Generated by Django 2.1.4 on 2018-12-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensorapp', '0002_sensor_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='roomName',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='roomType',
            field=models.CharField(blank=True, choices=[('Bathroom', 'Bathroom'), ('Livingroom', 'Living Room'), ('Bedroom', 'Bedroom')], default='Livingroom', max_length=512, null=True),
        ),
    ]
