# Generated by Django 2.1.4 on 2019-01-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensorapp', '0003_auto_20181221_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='humidity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='temperature',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='roomType',
            field=models.CharField(blank=True, choices=[('Bathroom', 'Bathroom'), ('Livingroom', 'Livingroom'), ('Bedroom', 'Bedroom')], default='Livingroom', max_length=512, null=True),
        ),
    ]
