# Generated by Django 2.1.4 on 2019-02-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensorapp', '0004_auto_20190115_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='roomName',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='roomType',
            field=models.CharField(blank=True, choices=[('Bathroom', 'Bathroom'), ('Livingroom', 'Livingroom'), ('Bedroom', 'Bedroom'), ('Kitchen', 'Kitchen'), ('Office', 'Office')], default='Livingroom', max_length=512, null=True),
        ),
    ]
