# Generated by Django 2.1.4 on 2019-02-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensorapp', '0008_auto_20190220_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='macAddress',
            field=models.CharField(max_length=17, primary_key=True, serialize=False, unique=True),
        ),
    ]
