# Generated by Django 2.1.4 on 2019-03-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensorapp', '0009_auto_20190221_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='roomType',
            field=models.CharField(blank=True, choices=[('Bathroom', 'Bathroom'), ('Livingroom', 'Livingroom'), ('Bedroom', 'Bedroom'), ('Kitchen', 'Kitchen'), ('Office', 'Office')], default='Livingroom', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='state',
            field=models.CharField(blank=True, choices=[('0', 'Not Connected'), ('1', 'No Data'), ('2', 'Climate is good!'), ('3', 'Too cold!'), ('4', 'Too hot!'), ('5', 'Too moist!'), ('6', 'Too dry!'), ('7', 'Too dry and too hot!'), ('8', 'Too dry and too cold!'), ('9', 'Too moist and too hot!'), ('10', 'Too moist and too cold!'), ('11', 'Error')], default='0', max_length=255, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=255, null=True, verbose_name='Gender'),
        ),
    ]
